// MIASMA-WORM / impersonation defense:
//
// The OLD implementation verified that SHA-256(pub_key || mac_addr || ip_addr)
// matched a stored `expected_hash`. This ONLY proves knowledge of the triplet —
// anyone who can observe the public key, MAC address, and IP address (all visible
// on the wire) can pre-compute the hash and pass the check without ever holding
// the corresponding private key.
//
// The NEW implementation requires a caller to present an Ed25519 SIGNATURE over
// a verifier-issued challenge bound to the identity:
//
//   signing_input = IDENTITY_PROOF_DOMAIN
//                   || challenge          (32 bytes, fresh per-verification random)
//                   || identity.pub_key   (32 bytes)
//                   || identity.mac_addr  ( 6 bytes)
//                   || identity.ip_addr   ( 4 bytes)
//
// This is a classic challenge-response proof of key possession. A network
// observer or supply-chain adversary who knows (pub_key, MAC, IP) but does NOT
// hold the private key CANNOT produce a valid signature, so impersonation is
// computationally infeasible under the Ed25519 security assumptions.
//
// Protocol:
//   1. Verifier generates 32-byte random challenge (NOT reused across calls).
//   2. Verifier sends challenge to the agent out-of-band.
//   3. Agent signs with Ed25519: sig = sign(priv_key, signing_input above).
//   4. Agent returns (TripartiteIdentity, sig).
//   5. Verifier calls verify_tripartite_identity(id, challenge, sig).

const IDENTITY_PROOF_DOMAIN: &[u8; 22] = b"LSES-IDENTITY-PROOF-V1";

#[no_mangle]
pub extern "C" fn verify_tripartite_identity(
    id: *const TripartiteIdentity,
    // 32-byte fresh random challenge generated by the verifier.
    // Must be unique per call; callers MUST NOT reuse challenges.
    challenge: *const u8,
    // 64-byte Ed25519 signature produced by the agent over signing_input.
    response_sig: *const u8,
) -> i32 {
    if id.is_null() || challenge.is_null() || response_sig.is_null() {
        return ERR_NULL_POINTER;
    }

    let identity = unsafe { &*id };
    let challenge_bytes = unsafe { core::slice::from_raw_parts(challenge, 32) };
    let sig_bytes: [u8; 64] = unsafe { core::ptr::read(response_sig as *const [u8; 64]) };

    // Reconstruct the exact same signing input the agent used.
    let mut signing_input =
        Vec::with_capacity(IDENTITY_PROOF_DOMAIN.len() + 32 + 32 + 6 + 4);
    signing_input.extend_from_slice(IDENTITY_PROOF_DOMAIN);
    signing_input.extend_from_slice(challenge_bytes);
    signing_input.extend_from_slice(&identity.pub_key);
    signing_input.extend_from_slice(&identity.mac_addr);
    signing_input.extend_from_slice(&identity.ip_addr);

    let verifying_key = match ed25519_dalek::VerifyingKey::from_bytes(&identity.pub_key) {
        Ok(k) => k,
        Err(_) => return ERR_CRYPTO,
    };
    let signature = ed25519_dalek::Signature::from_bytes(&sig_bytes);

    // verify_strict rejects low-order points and non-canonical encodings,
    // defending against related-key and small-subgroup attacks.
    match verifying_key.verify_strict(&signing_input, &signature) {
        Ok(_) => 0,
        Err(_) => ERR_AUTHENTICATION,
    }
}
